-- ====================================================================
-- CREAZIONE TABELLE
-- ====================================================================

-- 1. UTENTE1 (Aggiornata con colonna ATTIVO)
CREATE TABLE UTENTE1 (
    ID_UTENTE              NUMBER NOT NULL,
    EMAIL                  VARCHAR2(100 BYTE) NOT NULL,
    PASSWORD_HASH          VARCHAR2(255 BYTE) NOT NULL,
    DATA_CREAZIONE         DATE DEFAULT SYSDATE NOT NULL,
    ULTIMO_LOGIN           DATE,
    FOTO_PATH              VARCHAR2(500 BYTE),
    ATTIVO                 CHAR(1 BYTE) DEFAULT 'Y' NOT NULL, -- 'Y' = Attivo, 'N' = Disabilitato
    
    CONSTRAINT UTENTE1_PK PRIMARY KEY (ID_UTENTE),
    CONSTRAINT UTENTE1_EMAIL_U01 UNIQUE (EMAIL),
    CONSTRAINT UTENTE1_ATTIVO_CHK CHECK (ATTIVO IN ('Y', 'N'))
);

-- 2. RUOLO1
CREATE TABLE RUOLO1 (
    ID_RUOLO               NUMBER NOT NULL,
    CODICE_RUOLO           VARCHAR2(30 BYTE) NOT NULL,
    DESCRIZIONE            VARCHAR2(100 BYTE),
    CONSTRAINT RUOLO1_PK PRIMARY KEY (ID_RUOLO),
    CONSTRAINT RUOLO1_CODICE_U01 UNIQUE (CODICE_RUOLO)
);

-- 3. UTENTECOMPETENZASEDE1
CREATE TABLE UTENTECOMPETENZASEDE1 (
    ID_COMPETENZA          NUMBER NOT NULL,
    ID_UTENTE              NUMBER NOT NULL,
    ID_RUOLO               NUMBER NOT NULL, 
    CODSEDE_COMPETENZA     VARCHAR2(10 BYTE), -- NULL = Tutte le sedi
    
    CONSTRAINT UTCOMPSEDE1_PK PRIMARY KEY (ID_COMPETENZA),
    CONSTRAINT UTCOMPUTENTE1_FK FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE1 (ID_UTENTE) ON DELETE CASCADE,
    CONSTRAINT UTCOMPRUOLO1_FK FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO1 (ID_RUOLO) ON DELETE CASCADE,
    CONSTRAINT UTCOMPUNIVOCO1_U01 UNIQUE (ID_UTENTE, ID_RUOLO, CODSEDE_COMPETENZA)
);

-- ====================================================================
-- CREAZIONE SEQUENZE
-- ====================================================================
CREATE SEQUENCE SEQUTENTE1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQRUOLO1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQUTENTECOMPSEDE1 START WITH 1 INCREMENT BY 1 NOCACHE;

-- ====================================================================
-- CREAZIONE TRIGGER (AUTO-INCREMENTO ID)
-- ====================================================================
CREATE OR REPLACE TRIGGER TRGUTENTE1BI
BEFORE INSERT ON UTENTE1
FOR EACH ROW
BEGIN
    IF :NEW.ID_UTENTE IS NULL THEN
        SELECT SEQUTENTE1.NEXTVAL INTO :NEW.ID_UTENTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRGRUOLO1BI
BEFORE INSERT ON RUOLO1
FOR EACH ROW
BEGIN
    IF :NEW.ID_RUOLO IS NULL THEN
        SELECT SEQRUOLO1.NEXTVAL INTO :NEW.ID_RUOLO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRGUTCOMPSEDE1BI
BEFORE INSERT ON UTENTECOMPETENZASEDE1
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMPETENZA IS NULL THEN
        SELECT SEQUTENTECOMPSEDE1.NEXTVAL INTO :NEW.ID_COMPETENZA FROM DUAL;
    END IF;
END;
/

-- ====================================================================
-- CREAZIONE INDICI DI PERFORMANCE
-- ====================================================================
CREATE INDEX UTCOMPUTENTE1IDX ON UTENTECOMPETENZASEDE1 (ID_UTENTE);
CREATE INDEX UTCOMPSEDE1IDX ON UTENTECOMPETENZASEDE1 (CODSEDE_COMPETENZA);

-- ====================================================================
-- POPOLAMENTO INIZIALE DEI RUOLI
-- ====================================================================
INSERT INTO RUOLO1 (CODICE_RUOLO, DESCRIZIONE) VALUES ('ADMIN', 'Amministratore con permessi totali');
INSERT INTO RUOLO1 (CODICE_RUOLO, DESCRIZIONE) VALUES ('OPERATORE', 'Operatore abilitato alla modifica/inserimento');
INSERT INTO RUOLO1 (CODICE_RUOLO, DESCRIZIONE) VALUES ('VISUALIZZATORE', 'Utente in sola lettura');
COMMIT;